const { test, expect } = require('@playwright/test');
const {general_url, deploy_url} = require('../../urls');
const appFunctions = require('../../functions')
const passportSteps = require('../../Functions/passport')
const selectors = require('../../selectors')
const randomEmail = require('random-email')
let fastpassportEmail = randomEmail()

test('FastPassport - USPS Emergency', async({page}) => {
  test.slow()
  await page.goto(general_url + 'fastpassport.visachinaonline.com/passport-renewal/united-states')
  await page.reload()
  await page.getByRole('button').getByText('Start your renewal').click()
  await page.waitForURL('**/passport-renewal/united-states/application#step=step_1')
  const continue_sidebar = page.locator('#btnContinueSidebar')
  await continue_sidebar.click()
  
  await passportSteps.step_1_passport(page,  fastpassportEmail)
  await continue_sidebar.click()
  await passportSteps.step_3_passport(page)
  await continue_sidebar.click()

  await page.waitForTimeout(3000)
  const duplicate = await page.isVisible('id=btnDisclaimerNext')
  if (duplicate){
    await page.locator('id=btnDisclaimerNext').click()
  }
  await page.getByText("Emergency Service", {exact: true}).click()
  await page.waitForURL('**/passport-renewal/united-states/application#step=review')
  await appFunctions.newPaymentCheckout(page,"4111111111111111", "123", false)
  const payment_btn = page.locator('id=btnSubmitPayment')
  await expect(payment_btn).toBeVisible()
  await expect(payment_btn).toBeEnabled()
  await payment_btn.click()
  
  // Post Payment
  await page.waitForNavigation({waitUntil: 'load'})
  await page.getByTestId("transition-page-button").click()
  await selectors.phoneNumber(page)
  const next_btn = page.locator('id=btnContinueUnderSection')
  await page.waitForTimeout(1000)
  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  await page.waitForNavigation({waitUntil: 'load'})
  await page.waitForTimeout(2000)
  await selectors.dropdownSelector(page, "applicant.0.state_of_birth", "dropdown-applicant.0.state_of_birth", 'alaska', 'AK - ALASKA')
  await page.locator('[name="applicant.0.birth_city"]').fill('aaaaaaaaa')
  await selectors.dropdownSelector(page, "applicant.0.appearance_1", "dropdown-applicant.0.appearance_1", 'amber', 'Amber')
  await selectors.dropdownOptions(page, "dropdown-applicant.0.appearence_2", "Brown")
  await page.locator("id=feet-applicant.0.height_fsr").fill('5')
  await page.locator("id=inches-applicant.0.height_fsr").fill('5')
  await page.waitForTimeout(1000)
  await expect(next_btn).toBeEnabled()
  await next_btn.click()

  await selectors.booleanOptions(page, "applicant.0.marital_status", "boolean-Single")
  await selectors.booleanOptions(page, "applicant.0.father_information", "boolean-No")
  await selectors.booleanOptions(page, "applicant.0.mother_information", "boolean-No")

  await expect(next_btn).toBeEnabled()
  await next_btn.click()
  
  await page.waitForNavigation({waitUntil: 'load'})
  await page.locator('[name="applicant.0.ssn"]').click()
  await page.waitForTimeout(1000)
  await page.keyboard.type("123456")
  await page.waitForTimeout(1000)
  await page.keyboard.press('Enter')
  await expect(next_btn).toBeEnabled()
  await page.waitForTimeout(1000)
  await next_btn.click()
  await page.waitForNavigation({waitUntil: 'load'})
  await selectors.applicantPhoto(page)
  await selectors.passportPhoto(page)
  await selectors.datePicker(page, "applicant.0.passport_issued_date", "13", "7", "2012")
  await selectors.datePicker(page, "applicant.0.passport_expiration_date", "13", "7", "2023")
  await page.locator('[name="applicant.0.passport_num"]').fill('111111111')
  const submit_post_payment = page.locator("id=btnSubmitApplication")
  await submit_post_payment.click()
  await page.waitForNavigation({waitUntil: 'load'})
  const track_application = page.locator('#trackApplication')
  await expect(track_application).toBeVisible()
})