name: E2E (Playwright + Percy)

on:
  push:
    branches: [ "main" ]         
  
permissions:
  contents: read
  pages: write
  id-token: write           

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright with Percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          FLIGHT_API: ${{ secrets.FLIGHT_API }}
        shell: bash
        run: |
          set -o pipefail

          BUILD_ID=$(
            npx percy exec -- \
              npx playwright test \
                "tests/Travel documents/" \
                "tests/Passport-tests/" \
                "tests/Mobile/" \
                "tests/visual/" \
                --workers 4 \
            | grep -Eo 'https://percy.io/.*/builds/[0-9]+' \
            | awk -F/ '{print $NF}' \
            | tail -n1
          )

          echo "BUILD_ID=$BUILD_ID" >> "$GITHUB_ENV"
          echo "Captured BUILD_ID=$BUILD_ID"
          
      - name: Wait before generating Percy report
        run: sleep 50

      - name: Create Percy Report
        if: always()
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: npx percy-report generate "$BUILD_ID" --download-path "playwright-report"
      
      - name: Show files to be published
        run: |
          echo "Publishing these files:"
          find playwright-report -maxdepth 3 -type f | sort

      - name: Upload Playwright report to Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: playwright-report

      - name: Deploy to GitHub Pages
        if: always()
        uses: actions/deploy-pages@v4

      - name: Send results to slack
        if: ${{ always() }}
        run: node sendReport.js $BUILD_ID